version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'daily'
    groups:
      eslint:
        patterns:
          - '*eslint*'
    ignore:
      - dependency-name: 'eslint'
        update-types: ['version-update:semver-major']

  - package-ecosystem: 'github-actions'
    directory: '.github/workflows'
    schedule:
      interval: 'daily'
